name:                vinci-lang
version:             0.1.0.0
github:              "swtwsk/vinci-lang"
license:             BSD3
author:              "Andrzej Swatowski"
maintainer:          ""
copyright:           "2021 Andrzej Swatowski"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/swtwsk/vinci-lang#readme>

dependencies:
- base >= 4.7 && < 5
- array
# for now, because otherwise HLS doesn't see it
- tasty
- tasty-hunit

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  vinci-lang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - vinci-lang

tests:
  vinci-lang-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - vinci-lang
    - tasty
    - tasty-hunit
